### ISSUE TITLE
Unable to include ZME_WCD2 wall controller

### ISSUE THREAD

**Issue by MbenzNo** [priknr1/me.zwave#1]
I am unable to include a wall controller. I am unsure what firmware version it is, but it is at least 3-4 years old. It is labelled ZME_WCD2 on the backside. I have excluded it from my Vera Network and tried to include it in Homey as WallC-S and WallC-S V2 without luck.
To exclude/include it I have to set it in management mode and press button 3. It does not start inclusion with any other buttons. It is then detected, but after negotiation i get: No compatible Homey app found for this device.

Node ID: 26
Secure: No
Battery: Yes
Manufacturer ID: 277
Product ID: 4
Device Class (Basic): BASIC_TYPE_ROUTING_SLAVE
Device Class (Generic): GENERIC_TYPE_SWITCH_REMOTE
Device Class (Spesific): SPESIFIC_TYPE_SWITCH_REMOTE_MULTILEVEL

Manual for the device:
http://www.benext.eu/static/manual/zwaveme/double-wall-controller-WCD2-white.pdf

**Comment by priknr1** [comment]
When you try to add it, does it eventually add the device as a generic device?
When that is the case, click the wrench symbol, go to Node information, and find the Product type ID

Because to be able to add it I need the Product type ID to.  While you are there, please check if the Manufacturer ID and Device ID, are indeed the ones you provided above

**Comment by MbenzNo** [comment]
I obviously forgot the Product Type ID in my last post.
This is the information in the Node Information:

Node ID: 26
Secure: No
Battery: Yes
Manufacturer ID: 277
Product type ID: 256
Product ID: 4
Device Class (Basic): BASIC_TYPE_ROUTING_SLAVE
Device Class (Generic): GENERIC_TYPE_SWITCH_REMOTE
Device Class (Spesific): SPESIFIC_TYPE_SWITCH_REMOTE_MULTILEVEL

St1-R.

**Comment by priknr1** [comment]
Only the Product ID is different from the WALLC-S currently in the app. So I added yours blindly.
It is submitted to athom as Beta, and should appear in the app store under Beta in a day or 2. Please let me know if it is working

**Comment by MbenzNo** [comment]
Hi!

I installed the beta, rebooted Homey and reinstalled my WallC-S.

It seemed to install correctly, and I managed to have a look at the settings without altering anything. But now the app crashes just a couple of seconds after starting.

If I uninstall the WallC the app stops crashing.
If I re-install it as a generic Z-Wave device it is identified as a WALLC-S controller, but the app crashes after some seconds.

St1-R.

Sendt fra E-post for Windows 10

Fra: Patrick
Sendt: mandag 29. mai 2017 kl. 20.56
Til: priknr1/me.zwave
Kopi: MbenzNo; Author
Emne: Re: [priknr1/me.zwave] Unable to include ZME_WCD2 wall controller(#1)

Only the Product ID is different from the WALLC-S currently in the app. So I added yours blindly.
It is submitted to athom as Beta, and should appear in the app store under Beta in a day or 2. Please let me know if it is working

**Comment by priknr1** [comment]
I found that the ZME_WCD2 does not have setting 25, made a new device in the app, instead of adding your id to the WALLC-S.
Please check the beta version 0.1.3, (in appstore within days, or from this repository)

If it now works for you, please let me know.
And if you like my efforts, you can always buy me a beer with the donate button in the appstore.

**Comment by MbenzNo** [comment]
OK, I have loaded the beta Version 0.1.3, but I may have broken the wall Controller... It does not react as it is supposed to do, and is not recognised by Homey at all anymore. I have reset it an managed once to include it in my old Vera controller, but now both Vera and Homey will not recognise it anymore.  I will report back if I manage breathe life in it again...

**Comment by MbenzNo** [comment]
I am unable to do some more testing since my wall controller is broken. It seems that it somehow have corrupted data in the device itself. Homey will not recognise it at all. On my VeraPlus I sometimes manage to include it, but not "by the book". Factory reset fails with a blinking red light (Manage mode - click button 3 - then click and hold button 4 for more than 4 sec)
I will probably not buy a new one. I will replace it with a Fibaro ZW130

**Comment by priknr1** [comment]
Sorry to hear.
Does this mean I can/should  close this thread?
