### ISSUE TITLE
Any chance for Düwi remote (05445)?

### ISSUE THREAD

**Issue by sfredrikj** [priknr1/me.zwave#12]
Would it be possible to add support for the remote controll Düwi 05445?

Regards,
Fredrik

**Comment by priknr1** [comment]
I actually have one of those laying in the drawer unused for many years.
I cant seem to figure out how to get it to work in homey. So you'll need to find another programmer for this 
My programming skills simply do not reach.

This question has been asked before too, see other issues.

**Comment by priknr1** [comment]
Since this is a topic already in the issues list I will close this one.
