### ISSUE TITLE
Unable to install Z-Wave.me App

### ISSUE THREAD

**Issue by ghost** [priknr1/me.zwave#13]
I am unable to install the App on Homey. I attached a screenshot of the error message

![img_3692](https://user-images.githubusercontent.com/13766924/51071662-1745ea80-1655-11e9-9609-765ea19c7dc2.PNG)

**Comment by basd82** [comment]
I have the same isue in homey 2.0 @mapulu did you have fix if so how do install it ?

**Comment by cab10** [comment]
You could download the zip with the fixed file
https://github.com/priknr1/me.zwave/tree/798f84bf48474a3124c2f1547c1b8d9d33f6e414

and install it through CLI
https://forum.athom.com/discussion/1448/how-to-cli-install-method

**Comment by priknr1** [comment]
Sorry for the late response, did not get any notification about this. 
Going to upload to Athom, might take some days before they approve

**Comment by priknr1** [comment]
@Xtasy178  @mapulu 

The update is available in the appstore now, please let me know if things are working for you now.
